name: CI

on:
  pull_request:
  merge_group:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: exit 1
        if: ${{github.event_name == 'pull_request'}}
      - run: exit 0
        if: ${{github.event_name == 'merge_group'}}
